In [4]:
import pandas as pd
wineData = pd.read_csv('winequality-red.csv',delimiter=';')

In [2]:
wineData.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
wineData.duplicated().sum()

240

In [6]:
wineData.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [7]:
wineData.drop_duplicates(inplace=True)

In [8]:
x = wineData.iloc[:,:11]
y = wineData.iloc[:,11]
x
y

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

0       5
1       5
2       5
3       6
5       5
       ..
1593    6
1594    5
1595    6
1597    5
1598    6
Name: quality, Length: 1359, dtype: int64

In [7]:
wineData.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [9]:
import sklearn.preprocessing as ps
import numpy as np
scaler = ps.StandardScaler()
from sklearn.compose import make_column_transformer
transformer = make_column_transformer((scaler, ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']))
px = transformer.fit_transform(x)
py = scaler.fit_transform(np.c_[y])

In [10]:
px.shape

(1359, 11)

In [11]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import models
model = models.Sequential()
model.add(layers.Dense(100, input_dim=11 , activation='relu'))
model.add(layers.Dense(75 , activation='relu'))
model.add(layers.Dense(50 , activation='relu'))
model.add(layers.Dense(20 , activation='relu'))
model.add(layers.Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               1200

 dense_1 (Dense)             (None, 75)                7575

 dense_2 (Dense)             (None, 50)                3800

 dense_3 (Dense)             (None, 20)                1020

 dense_4 (Dense)             (None, 1)                 21

=================================================================
Total params: 13,616
Trainable params: 13,616
Non-trainable params: 0
_________________________________________________________________

In [12]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse'])

In [13]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(px,py)

In [14]:
model.fit(train_x,train_y, epochs=50)

Epoch 1/50
32/32 [==============================] - 1s 2ms/step - loss: 0.7833 - mse: 0.7833
Epoch 2/50
32/32 [==============================] - 0s 2ms/step - loss: 0.6400 - mse: 0.6400
Epoch 3/50
32/32 [==============================] - 0s 3ms/step - loss: 0.5960 - mse: 0.5960
Epoch 4/50
32/32 [==============================] - 0s 2ms/step - loss: 0.5740 - mse: 0.5740
Epoch 5/50
32/32 [==============================] - 0s 2ms/step - loss: 0.5422 - mse: 0.5422
Epoch 6/50
32/32 [==============================] - 0s 2ms/step - loss: 0.5225 - mse: 0.5225
Epoch 7/50
32/32 [==============================] - 0s 2ms/step - loss: 0.5107 - mse: 0.5107
Epoch 8/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4929 - mse: 0.4929
Epoch 9/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4758 - mse: 0.4758
Epoch 10/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4646 - mse: 0.4646
Epoch 11/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4415 - mse: 0.4415
Epoch 12/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4352 - mse: 0.4352
Epoch 13/50
32/32 [==============================] - 0s 2ms/step - loss: 0.4067 - mse: 0.4067
Epoch 14/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3960 - mse: 0.3960
Epoch 15/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3839 - mse: 0.3839
Epoch 16/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3664 - mse: 0.3664
Epoch 17/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3493 - mse: 0.3493
Epoch 18/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3437 - mse: 0.3437
Epoch 19/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3393 - mse: 0.3393
Epoch 20/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3149 - mse: 0.3149
Epoch 21/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3092 - mse: 0.3092
Epoch 22/50
32/32 [==============================] - 0s 2ms/step - loss: 0.3013 - mse: 0.3013
Epoch 23/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2763 - mse: 0.2763
Epoch 24/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2699 - mse: 0.2699
Epoch 25/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2708 - mse: 0.2708
Epoch 26/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2481 - mse: 0.2481
Epoch 27/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2384 - mse: 0.2384
Epoch 28/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2348 - mse: 0.2348
Epoch 29/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2141 - mse: 0.2141
Epoch 30/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2044 - mse: 0.2044
Epoch 31/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2176 - mse: 0.2176
Epoch 32/50
32/32 [==============================] - 0s 2ms/step - loss: 0.2030 - mse: 0.2030
Epoch 33/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1945 - mse: 0.1945
Epoch 34/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1812 - mse: 0.1812
Epoch 35/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1786 - mse: 0.1786
Epoch 36/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1671 - mse: 0.1671
Epoch 37/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1596 - mse: 0.1596
Epoch 38/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1595 - mse: 0.1595
Epoch 39/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1455 - mse: 0.1455
Epoch 40/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1486 - mse: 0.1486
Epoch 41/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1361 - mse: 0.1361
Epoch 42/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1317 - mse: 0.1317
Epoch 43/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1335 - mse: 0.1335
Epoch 44/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1299 - mse: 0.1299
Epoch 45/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1308 - mse: 0.1308
Epoch 46/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1372 - mse: 0.1372
Epoch 47/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1240 - mse: 0.1240
Epoch 48/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1075 - mse: 0.1075
Epoch 49/50
32/32 [==============================] - 0s 2ms/step - loss: 0.1007 - mse: 0.1007
Epoch 50/50
32/32 [==============================] - 0s 2ms/step - loss: 0.0953 - mse: 0.0953

In [15]:
pred_uy=model.predict(test_x)
pred_y = scaler.inverse_transform(pred_uy)
tested_y = scaler.inverse_transform(test_y)

11/11 [==============================] - 0s 3ms/step

In [15]:
wineData.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [16]:
wineData.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

In [25]:
import numpy as np
fixed_acidity = float(input("Enter fixed acidity: "))
volatile_acidity = float(input("Enter volatile acidity: "))
citric_acid = float(input("Enter the value of citric acid: "))
residual_sugar = float(input("Enter the value of residual sugar: "))
chlorides = float(input("Enter the value of chlorides: "))
free_sulfur_dioxide = float(input("Enter the value of chlorides: "))
total_sulfur_dioxide = float(input("Enter the value of total sulfur dioxide: "))
density = float(input("Enter the value of density: "))
pH = float(input("Enter pH value: "))
sulphates = float(input("Enter the value of sulphates: "))
alcohol = float(input("Enter the value of alcohal: "))
sample = pd.DataFrame({'fixed acidity':fixed_acidity, 'volatile acidity':volatile_acidity,'citric acid': citric_acid,'residual sugar': residual_sugar,
   'chlorides':chlorides, 'free sulfur dioxide':free_sulfur_dioxide,'total sulfur dioxide': total_sulfur_dioxide, 'density':density,
   'pH':pH, 'sulphates':sulphates, 'alcohol':alcohol},index=[0])

Enter fixed acidity: 11.2
Enter volatile acidity: 0.28
Enter the value of citric acid: 0.56
Enter the value of residual sugar: 1.9
Enter the value of chlorides: 0.075
Enter the value of chlorides: 17.0
Enter the value of total sulfur dioxide: 60.0
Enter the value of density: 0.9980
Enter pH value: 3.16
Enter the value of sulphates: 0.58
Enter the value of alcohal: 9.8

In [24]:
wineData.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

In [27]:
psample=transformer.fit_transform(sample)
res=model.predict(sample)
ires = scaler.inverse_transform(res)
print(ires)

1/1 [==============================] - 0s 20ms/step
[[-8.334763]]